## 제어 흐름과 에러 처리


### 목표

JavaScript는 어플리케이션 상의 상호작용을 통합하는데 사용할 수 있는 일련의 문법, 특히 제어흐름 문을 지원합니다. 이 장에서는 이러한 문법의 개요를 알아봅니다.


### Block 문

- 대괄호 ( { } )에 의해 범위가 결정
- 일반적으로 제어 흐름 문(if, for, while)과 함께  사용
- ECMAScript 6 이전의 JavaScript는 블록 범위를 가지고 있지 않음
- ECMAScript 6부터, let 변수 선언으로 변수의 블록 범위를 제한 가능


### 조건문

- 특정 조건이 참인 경우에 실행하는 명령의 집합(if... else & switch)

#### if...else 문

- 특정 조건이 참인 경우 문장을 실행하기 위해 if 문을 사용
- 선택적으로 조건이 거짓인 경우 문장을 실행하기 위해서는 else 절을 사용
- 조건문 안에서의 변수값 할당은 사용하지 않는 것이 좋습니다. 왜냐하면 그것은 코드를 자세히 보지 않는 경우, 동등비교연산자로 오해

```JavaScript
if (x = y) {
  /* statements here */
}
```


- 할당 주위에 추가 괄호를 넣는 것

```JavaScript
if ((x = y)) {
  /* statements here */
}
```

- 거짓으로 취급하는 값
    + false
    + undefined
    + null
    + 0
    + NaN
    + the empthstring("")


#### switch 문

- 표현식을 평가하고 값을 조건과 비교합니다. 만약 값이 일치한다면, 프로그램은 각 조건의 하위 문장을 실행

```JavaScript
switch (expression) {
  case label_1:
    statements_1
    [break;]
  case label_2:
    statements_2
    [break;]
    ...
  default:
    statements_def
    [break;]
}
```

- 관례상, default 절은 마지막절
- 만약 break문이 생략된다면, 그 프로그램은 switch문안에서 다음 문장을 계속 수행


### 예외처리문


#### 예외유형

- ECMAScript exceptions
    + Standard objects(global objects)들의 예외
- DOMException
    + an abnormal event (called an exception) which occurs as a result of calling a method or accessing a property of a web API. This is basically how error conditions are described in web APIs.
- DOMError
    + an error object that contains an error name.

#### throw 문

- 사용되는 값을 포함하는 표현을 명시
```JavaScript
throw "Error2";   // String type
throw 42;         // Number type
throw true;       // Boolean type
throw {toString: function() { return "I'm an object!"; } };
```

#### try...catch 문법

- 시도할 블록을 표시하고, 예외가 발생하였을때, 하나 이상의 반응을 명시
- 하나 이상의 문장을 포함한 try 블록과, try 블록 에서 예외가 발생하였을때, 어떤 것을 할 것인지 명시된 문장을 포함한 1개 이상의 catch 블록으로 구성
- 만약 try 블록(또는 try 블록에서 호출하는 함수) 의 문장이 예외를 발생시켰을때, 제어는 즉시 catch 블록으로 이동
- 만약 try 블록에서 예외가 발생하지 않았을 때, catch 블록을 건너뜀
- finally 블록은 try 블록과 catch 블록의 시행이 끝나고 try...catch 문법 다음의 문장이 시행 되기 전에 시행


##### catch 블록

- catch 블록은 throw문장에 의해 명시된 값을 가지고 있는 식별자(앞 구문의 catchID)를 명시
- 별자는 catch 블록에 있는 동안만 유지


##### finally 블록

- finally 블록은 try 블록과 catch 블록이 시행되고, try...catch 문법 다음 문장이 시행되기 전에 시행되는 문장들을 포함
- finally 블록을 예외가 발생하였을때 여러분의 스크립트가 우아하게 실패하도록 만들기 위하여 사용
- finally 블록이 값을 반환하였을 경우, try 블록과 catch블록의 return 문장과 상관없이 전체 try-catch-finally 생산물의 반환값


### Error 객체를 도구화 하기

-더 정제된 메세지를 얻기 위하여 'name'속성과 'message'속성을 사용할 수 있음

```JavaScript
function doSomethingErrorProne () {
  if (false) {
    throw (new Error('The message'));
  } else {
    doSomethingToGetAJavascriptError();
  }
}
....
try {
  doSomethingErrorProne();
}
catch (e) {
  console.log(e.name); // logs 'Error'
  console.log(e.message); // logs 'The message' or a JavaScript error message)
}
```


### Promise

- ECMAScript 6를 시작하면서, 자바스크립트는 지연된 흐름과 비동기식의 연산을 제어할 수 있게 하는 Promise 객체에 대한 지원
- Promise는 아직은 아니지만 나중에 완료될 것으로 기대되는 연산을 표현
- promise의 상태
    + pending(대기중): 초기상태, fulfilled 되거나 rejected 되지 않음.
    + fulfilled(이행됨): 연산 수행 성공.
    + rejected(거부됨): 연산 수행 실패.
    + settled: Promise 가 fulfilled 이거나 rejected 이지만 pending 은 아님.
